spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kenko?SQLuseSSL=false
    username: root
    password: 741994leo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect